### ISSUE TITLE
Do not seem to work with SvelteKit and MDX

### ISSUE THREAD

**Issue by Hunam6** [xiphux/rehype-svimg#7]
Here's a minimal reproduction repo: https://github.com/Hunam6/minimal-repo-svimg.

- I created a SvelteKit app using `npm init svelte@next my-app`
- I've installed `mdsvex` (MDX for Svelte)
- I've installed `retype-svimg`
- I've configured both packages in [`svelte.config.js`](https://github.com/Hunam6/minimal-repo-svimg/blob/main/svelte.config.js)
- When running `npm run dev` the HTML custom element gets generated 👍
- In [`index.md`](https://github.com/Hunam6/minimal-repo-svimg/blob/main/index.md) I've imported `svimg/dist/s-image` and it just throws an error:
```js
TypeError: Class extends value undefined is not a constructor or null
    at /Users/hunam/Documents/dev/minimalrepo-svimg/node_modules/svimg/dist/s-image.js:714:25
    at Object.<anonymous> (/Users/hunam/Documents/dev/minimalrepo-svimg/node_modules/svimg/dist/s-image.js:887:2)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at nodeRequire (/Users/hunam/Documents/dev/minimalrepo-svimg/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66559:17)
    at ssrImport (/Users/hunam/Documents/dev/minimalrepo-svimg/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66501:20)
```
---
I hope I explained it well!

**Comment by xiphux** [comment]
Custom elements like s-image only work on the client side and not during SSR; they depend on client-only concepts like `document` and `HTMLElement` - specifically HTMLElement doesn't exist for this particular error. A standard import like this would happen on both the client and server.

Try one of these options, maybe vite-plugin-iso-import: <https://kit.svelte.dev/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window>

**Comment by Hunam6** [comment]
Thanks for answering that quickly I understand why it didn't work!

I managed to make it work by installing the Vite plugin "vite-plugin-iso-import", putting it inside the config file and appending the `?client` suffix. Another way is to use the `onMount` function so the you don't have to install another package.

Anyway it kinda work but I don't understand why I only have a blurred image, here's a screenshot with the Svelte starter favicon:
<img width="1552" alt="Screenshot 2021-12-08 at 14 57 35" src="https://user-images.githubusercontent.com/38606542/145220722-17d367c3-a182-4d9b-a77e-8a746b4b0b1a.png">

**Comment by Hunam6** [comment]
It seems to be another issue though, should I create another one?

**Comment by xiphux** [comment]
Check the [Usage section of the README](https://github.com/xiphux/rehype-svimg#usage) - by default the plugin doesn't generate the actual optimized image, expecting it to be handled during the build step with a rollup plugin. So it's blurred because the file it's trying to lazy load doesn't exist. You can tell the plugin to generate the images by setting the `generateImages` parameter, but there are downsides to doing this depending on what kind of project you're creating.
